[theme]

# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#D4F1F4"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffff"

# Color used for almost all text.
textColor = "#000C66"